### ISSUE TITLE
卡在正在加载

### ISSUE THREAD

**Issue by waycowei** [yrming/vscode-yuque#3]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/8675871/166302477-316b3caf-0d45-432a-ae17-5f8e3714037c.png">

VSCode 版本 March 2022 (version 1.66)

**Comment by yrming** [comment]
@waycowei 无法复现，打开「帮助-切换开发人员工具」看下是否有报错信息。

**Comment by KagurazakaNyaa** [comment]
在扩展宿主的日志中可以得到
```
[2022-05-05 18:39:30.369] [exthost] [error] Error: Unable to set tempRootPath.
	at YuqueSettings.setTempRootPath (c:\Users\Admin\.vscode\extensions\yrm.yuque-0.1.8\out\yuque\settings.js:129:19)
	at new YuqueSettings (c:\Users\Admin\.vscode\extensions\yrm.yuque-0.1.8\out\yuque\settings.js:25:34)
	at Function.init (c:\Users\Admin\.vscode\extensions\yrm.yuque-0.1.8\out\yuque\settings.js:29:35)
	at activate (c:\Users\Admin\.vscode\extensions\yrm.yuque-0.1.8\out\extension.js:9:24)
	at Function._callActivateOptional (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:16070)
	at Function._callActivate (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:15731)
	at c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:13549
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async g._activate (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8154)
	at async g._waitForDepsThenActivate (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8096)
	at async g._initialize (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:7460)
```

**Comment by yrming** [comment]
@waycowei @KagurazakaNyaa 已修复，请安装最新版本。
